# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='タイトル')),
                ('question', models.TextField(max_length=1024, verbose_name='問題文')),
                ('answer', models.CharField(max_length=256, verbose_name='正解')),
            ],
        ),
    ]
